### ISSUE TITLE
slowernews.com

### ISSUE THREAD

**Issue by slowernews** [karan/nojs.club#10]
Domain: https://www.slowernews.com

GTMetrix: https://gtmetrix.com/reports/www.slowernews.com/Qitl8DU3/

You can navigate with JS disabled without any problem. The only JS is for minimal analytics. I'm even considering to use a pixel instead.

**Comment by slowernews** [comment]
You can navigate with JS disabled without any problem. The only JS is for minimal analytics. I'm even considering to use a pixel image instead.

**Comment by karan** [comment]
Sorry, no JavaScript
