### ISSUE TITLE
https://cyberia.host doesn't load

### ISSUE THREAD

**Issue by coltonhurst** [karan/nojs.club#17]
In case you know the owner of the website, just wanted to let people know- the site is not loading for me or GeoPeeker.

https://cyberia.host

**Comment by karan** [comment]
Seems fine.

![image](https://user-images.githubusercontent.com/3261985/100489701-bd286400-30ca-11eb-8f61-8e9739cb2758.png)

**Comment by coltonhurst** [comment]
@karan I see the issue now.

Your screenshot shows the site with http. The link on https://nojs.club/ is with https. They don't seem to have a cert so the https link doesn't work.
