### ISSUE TITLE
Links have same colour as text

### ISSUE THREAD

**Issue by SaphireLattice** [karan/nojs.club#51]
In the description about "why js is bad", links have exactly same color as plain text and are not recognizable as such, e.g. you can't know that word "accessibility" is actually a link unless you hover on it and see that it changes color.

Firefox Developer Edition 84.0b3

**Comment by karan** [comment]
I'm happy to make them better, but they do meet the criteria at https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Styling_links:

> Use underlining for links, but not for other things. If you don't want to underline links, at least highlight them in some other way.
> Make them react in some way when hovered/focused, and in a slightly different way when activated.

If you have other definitive/authoritative sources in mind, or specific suggestions, I'm happy to make the change.

**Comment by SaphireLattice** [comment]
Ah whoops. It seems that I have disabled underlining of links by default on my side in own browser preferences. This is first time that this has come up as relevant, so I did not realize I disabled that some time ago. Sorry for this! Perhaps making sure that there is underline style set even if browser did not would be good?

**Comment by karan** [comment]
I don't think I want to override the browser's behavior.
