### ISSUE TITLE
mkws.sh

### ISSUE THREAD

**Issue by adriangrigore** [karan/nojs.club#58]
Domain:  mkws.sh
GTMetrix: https://gtmetrix.com/reports/mkws.sh/zcdYG0hy/

I think it respects the idea behind nojs.club in spirit?

**Comment by karan** [comment]
( ͡° ͜ʖ ͡°)

https://en.wikipedia.org/wiki/PRISM_%28surveillance_program%29

**Comment by adriangrigore** [comment]
But it's this Prism https://prismjs.com/, it's progressively enhanced. So it's a no go?

**Comment by karan** [comment]
Sorry, no!
